# Generated by Django 4.0.3 on 2022-04-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addimission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_status', models.CharField(choices=[('1', 'Passed'), ('2', 'Appeared')], db_column='exam_status', default='1', max_length=9)),
                ('exam_name', models.CharField(db_column='exam_name', max_length=50)),
                ('exam_year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], db_column='exam_year', verbose_name='exam year')),
                ('board_name', models.CharField(db_column='board_name', max_length=50)),
                ('student_first_name', models.CharField(db_column='student_first_name', max_length=20)),
                ('student_middle_name', models.CharField(db_column='student_middle_name', max_length=20)),
                ('student_last_name', models.CharField(db_column='student_last_name', max_length=20)),
                ('blood_group', models.CharField(choices=[('O+', 'O Positive'), ('O-', 'O Negative'), ('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], db_column='blood_group', max_length=12)),
                ('phone_number', models.CharField(db_column='phone_number', max_length=10)),
                ('email_address', models.EmailField(db_column='email_address', max_length=254)),
                ('caste', models.CharField(db_column='caste', max_length=50)),
                ('sub_caste', models.CharField(choices=[('S', 'Shwetamber'), ('D', 'Digamber')], db_column='sub_caste', max_length=11)),
                ('birth_date', models.DateField(db_column='birth_date')),
                ('age', models.IntegerField(db_column='age')),
                ('formally_admitted', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], db_column='formally_admitted', max_length=3)),
                ('if_admitted', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], db_column='if_admitted', verbose_name='admitted year')),
                ('father_first_name', models.CharField(db_column='father_first_name', max_length=20)),
                ('father_middle_name', models.CharField(db_column='father_middle_name', max_length=20)),
                ('father_last_name', models.CharField(db_column='father_last_name', max_length=20)),
                ('father_occupation', models.CharField(db_column='father_occupation', max_length=50)),
                ('college_name', models.CharField(db_column='college_name', max_length=80)),
                ('course_name', models.CharField(db_column='course_name', max_length=50)),
                ('semister', models.IntegerField(db_column='semister')),
                ('last_year_appeared_exam_name', models.CharField(db_column='last_year_appeared_exam_name', max_length=50)),
                ('fill_marks', models.FloatField(db_column='fill_marks')),
                ('other_achievements', models.CharField(db_column='other_achievements', max_length=80)),
                ('at_present_working', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], db_column='at_present_working', max_length=4)),
                ('company_address', models.TextField(db_column='company_address')),
                ('salary', models.IntegerField(db_column='salary')),
                ('parent_full_name', models.CharField(db_column='parent_full_name', max_length=100)),
                ('pamanent_address', models.TextField(db_column='pamanent_address')),
                ('permanent_city', models.CharField(db_column='permanent_city', max_length=20)),
                ('pincode', models.CharField(db_column='pincode', max_length=6)),
                ('parent_phone_number', models.CharField(db_column='parent_phone_number', max_length=10)),
                ('parent_telephone_number', models.CharField(db_column='parent_telephone_number', max_length=10)),
                ('parent_email_address', models.EmailField(db_column='parent_email_address', max_length=254)),
                ('guardian_email_address', models.EmailField(db_column='guardian_email_address', max_length=254)),
                ('guardian_first_name', models.CharField(db_column='guardian_first_name', max_length=20)),
                ('guardian_middle_name', models.CharField(db_column='guardian_middle_name', max_length=20)),
                ('guardian_last_name', models.CharField(db_column='guardian_last_name', max_length=20)),
                ('guardian_phone_number', models.CharField(db_column='guardian_phone_number', default='', max_length=10)),
                ('local_address', models.TextField(db_column='local_address')),
                ('local_pincode', models.CharField(db_column='local_pincode', max_length=6)),
                ('guardian_telephone_number', models.CharField(db_column='guardian_telephone_number', max_length=10)),
                ('history_of_medical_illness', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], db_column='history_of_medical_illness', max_length=3)),
                ('taking_medicines', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], db_column='taking_medicines', max_length=3)),
                ('medicine_name', models.CharField(db_column='medicine_name', max_length=20)),
                ('student_photo', models.ImageField(upload_to='images/student_photos/')),
            ],
            options={
                'db_table': 'addmission',
                'managed': True,
            },
        ),
    ]
