# Generated by Django 4.0.3 on 2022-04-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_rename_addimission_admission'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admission',
            table='admission',
        ),
    ]
